---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: csharp-rest-service-x2
  labels:
    apps.tanzu.vmware.com/workload-type: web-j
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: csharp-rest-service
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: csharp-rest-service
    tanzu.app.live.view.application.actuator.port: "9090"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/swagger/v1/swagger.json"  # The path to the api documentation
      owner: OWNER_VAL
      system: SYSTEM_VAL
      description: DESCRIPTION_VAL
  - name: jenkins_final_pipeline_params
    value:
      #! Required: Name of the Jenkins job
      job-name: tap-finalizer
      #! Required: The secret created earlier to access Jenkins
      secret-name: jenkins-secret
      #! Required: The `job-params` element is required, but the parameter string
      #! should be empty for this jenkins integration. If empty, then set this value to `[]`
      job-params: "[]"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/jaimegag/csharp-rest-service
      ref:
        branch: main

  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database