apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
type: Opaque
stringData:
  url: http://jenkins.tkg-vsp-lab.hyrulelab.com/
  username: "changeme"
  password: "changeme!"
#  ca-cert: <PEM-encoded CA certificate>