apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: jenkins-final-task
spec:
  params:
  - name: gitops-repo
    type: string
  - name: gitops-branch
    type: string
  - name: gitops-subpath
    type: string
  - name: secret-name
    type: string
  - name: job-name
    type: string
  - default: ""
    name: job-params
    type: string
  results:
  - name: jenkins-job-url
    type: string
  steps:
  - args:
    - /trigger
    - -job
    - $(params.job-name)
    - -job-url-result-path
    - /tekton/results/jenkins-job-url
    - -parameters
    - $(params.job-params)
    env:
    - name: JENKINS_HOST_URL
      valueFrom:
        secretKeyRef:
          key: url
          name: $(params.secret-name)
    - name: JENKINS_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: $(params.secret-name)
    - name: JENKINS_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: password
          name: $(params.secret-name)
    - name: JENKINS_CA_CERT
      valueFrom:
        secretKeyRef:
          key: ca-cert
          name: $(params.secret-name)
          optional: true
    - name: gitops-repo
      value: $(params.gitops-repo)
    - name: gitops-branch
      value: $(params.gitops-branch)
    - name: gitops-subpath
      value: $(params.gitops-subpath)
    image: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap/tap-packages@sha256:7e201eeb489fcf861998cc27faa581d0e38472068dffb195eb26ba5769fed262
    name: trigger-jenkins-build
    resources: {}