---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-jenkins-final-tekton-pipeline
  namespace: myapps
spec:
  results:
  - name: jenkins-job-url   #! To show the job URL on the
    #! Tanzu Application Platform GUI
    value: $(tasks.jenkins-final-task.results.jenkins-job-url)
  params:
  - name: secret-name       #! Required
  - name: job-name          #! Required
  - name: job-params        #! Required
  - name: gitops-repo
  - name: gitops-branch
  - name: gitops-subpath
  - name: source-url
  tasks:
  #! Required: Include the built-in task that triggers the
  #! given job in Jenkins
  - name: jenkins-final-task
    taskRef:
      name: jenkins-final-task
      kind: ClusterTask
    params:
      - name: secret-name
        value: $(params.secret-name)
      - name: job-name
        value: $(params.job-name)
      - name: job-params
        value: $(params.job-params)
      - name: gitops-repo   # Keeping for future review: they are not being passed to the Jenkins job call
        value: $(params.gitops-repo)
      - name: gitops-branch   # Keeping for future review: they are not being passed to the Jenkins job call
        value: $(params.gitops-branch)
      - name: gitops-subpath   # Keeping for future review: they are not being passed to the Jenkins job call
        value: $(params.gitops-subpath)
      - name: source-url   # Keeping for comparison: being passed to the Jenkins job call, but not needed
        value: $(params.source-url)